### ISSUE TITLE
minus sign in JSON names

### ISSUE THREAD

**Issue by michael-oneill** [mikewest/first-party-sets#4]
Although its possible to access JS objects where the name includes reserved characters e.g. myObject["first-party-set"], it is a bit clumsy. Can we camel case the name e.g. firstPartySet,
so we can write myObject.firstPartySet?

I just noticed this is recommended in the [Google JSON style guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format).

**Comment by mikewest** [comment]
Thanks for calling this out, `-` is certainly a bad idea. I'll likely end up running with the TAG's recommendations to underscore-delimit JSON keys (https://w3ctag.github.io/design-principles/#casing-rules). That is, `{ "first_party_set": [ ... ] }`.

If we create a mechanism to access the first-party set details from JavaScript directly, we can certainly do so in a way that follows the camel-case recommendations for Web IDL dictionary keys. This document doesn't actually do that, and it's not clear to me that it would be a good idea to do so. But there might well be a use case I'm missing?

**Comment by michael-oneill** [comment]
Underscore will do it just as well. I was thinking it might be useful to make the first_party_sites array available to javascript so the JSON could be automatically parsed, or script could do an XHR to get it.
Another issue springs to mind from that, should the .well-known resource be CORS enabled so it could be loaded cross-origin? It could then be accessible to the other domains in the set (by the server checking Origin points to one of the set)
